header:
    text: "Nite, a revolutionary drinking card system for NightClubs or Bars."
    button: "Find out more!"

services:
    title: "Services"
    text: "Lorem ipsum"
    section: services
    list:
      - title: "E-Commerce"
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
        icon: fas fa-shopping-cart #find more at https://fontawesome.com/icons
      - title: "Responsive Design"
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
        icon: fas fa-laptop
      - title: "[Markdown](https://en.wikipedia.org/wiki/Markdown)"
        desc: "Your description here, full **Markdown** support"
        icon: fab fa-markdown

portfolio:
    title: "Portfolio"
    text: "Lorem ipsum dolor sit amet consectetur."
    section: portfolio
    closebutton: "Close Project"


timeline:
    title: "About"
    text: "Lorem ipsum timeline"
    section: timeline
    # left is the default
    #start_align: "left"
    events:
      - title: "Our Humble Beginnings"
        year: "2009-2011"
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
        image: assets/img/timeline/1.jpg
        alt:
      - title: "An Agency is Born"
        year: "March 2011"
        desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
        image: assets/img/timeline/2.jpg
        alt:
      - title: "Jekyll Theme is created"
        year: "2019"
        desc: "Ravi Riley converted Agency, a Bootstrap-based theme, into a Jekyll theme. The Jekyll theme can be installed as a Ruby gem, or remotely. For more information, visit the documentation."
        image: assets/img/timeline/3.jpg
        alt: image alt text
      - title: "Title"
        year: "2009-2011"
        desc: "Your description here, **Markdown** is fully supported."
        image: assets/img/timeline/4.jpg
        alt:
        # you can enforce the aligment
        align: right
    end: "Be Part <br> of Our <br> Story!"

about:
    title: "About Us"
    text: "our story"
    section: about

clients:
    section: clients
    max-height: 100px
    horizontal-scrolling: "" #"yes/no"
    list:
      - title: "envato"
        url: https://github.com/raviriley/agency-jekyll-theme
        logo: assets/img/clients/envato.jpg
      - title: "designmodo"
        url: https://github.com/raviriley/agency-jekyll-theme
        logo: assets/img/clients/designmodo.jpg
      - title: "themeforest"
        url: https://github.com/raviriley/agency-jekyll-theme
        logo: assets/img/clients/themeforest.jpg
      - title: "Creative Market"
        url: https://github.com/raviriley/agency-jekyll-theme
        logo: assets/img/clients/creative-market.jpg

team:
    title: "OUR AMAZING TEAM"
    text: "Lorem ipsum dolor sit amet consectetur."
    subtext: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde. **Markdown** supported.
    section: team
    people:
      - name: "Filipa Pereira"
        role: "Frontend dev"
        image: /assets/img/team/ffp.jpg
        social:
          - url: https://github.com/FilipaPereira
            icon: fab fa-github
      - name: "Diogo Sobral"
        role: "Lead Frontend dev & Team Manager"
        image: /assets/img/team/fds.JPG
        social:
          - url: https://github.com/dakrs
            icon: fab fa-github
          - url: https://www.linkedin.com/in/dsobral54/
            icon: fab fa-linkedin-in
      - name: "Mariana Pereira"
        role: "Frontend dev"
        image: /assets/img/team/fmp.jpeg
        social:
          - url: https://twitter.com
            icon: fab fa-github
          - url: https://linkedin.com
            icon: fab fa-linkedin-in
      - name: "Maria Dias"
        role: "Lead Frontend dev"
        image: /assets/img/team/fmd.png
        social:
          - url: https://github.com/mariadias143
            icon: fab fa-github
          - url: https://www.linkedin.com/in/mariadias143/
            icon: fab fa-linkedin-in
      - name: "Nuno Silva"
        role: "Frontend dev"
        image: /assets/img/team/fns.jpg
        social:
          - url: https://github.com/mineiro25
            icon: fab fa-github
          - url: https://www.linkedin.com/in/nunosilva25/
            icon: fab fa-linkedin-in
      - name: "Bruno Pereira"
        role: "Lead Frontend dev"
        image: /assets/img/team/fbp.jpg
        social:
          - url: https://github.com/b-pereira
            icon: fab fa-github
          - url: https://www.linkedin.com/in/bgpereira/
            icon: fab fa-linkedin-in
      - name: "Francisco Freitas"
        role: "Lead Backend Dev"
        image: /assets/img/team/fff.jpg
        social:
          - url: https://github.com/FranciscoFreitas45
            icon: fab fa-github
          - url: https://www.linkedin.com/in/francisco-freitas-5bb056115/
            icon: fab fa-linkedin-in
          - url: https://www.instagram.com/zefreitas45/
            icon: fab fa-instagram
      - name: "Pedro Freitas"
        role: "Backend Dev"
        image: /assets/img/team/fpf.jpg
        social:
          - url: https://github.com/PedroFreitas90
            icon: fab fa-github
          - url: https://www.linkedin.com/in/pedrofreitas90/
            icon: fab fa-linkedin-in
      - name: "Hugo Gião"
        role: "Backend Dev"
        image: /assets/img/team/500x500.jpg
        social:
          - url: https://twitter.com
            icon: fab fa-github
          - url: https://linkedin.com
            icon: fab fa-linkedin-in


contact:
    title: "Contact Us"
    text: "Lorem ipsum or call 123456789"
    section: contact

footer:
    legal: "Privacy Policy"
    social:
      - url: https://twitter.com
        icon: "fab fa-twitter"
      - url: https://facebook.com
        icon: "fab fa-facebook-f"
      - url: https://linkedin.com
        icon: "fab fa-linkedin-in"
      - url: https://github.com/raviriley/agency-jekyll-theme
        icon: "fab fa-github"
      - url: https://instagram.com
        icon: "fab fa-instagram"

promises:
  title: "For an establishment"
  subtitle: "With"
  first_promise_name: "Mobile Payments"
  first_promise_text: "Allowing a consumer to pay with his mobile phone"
  snd_promise_name: "Digital Consumption Cards"
  snd_promise_text: "A digital simulation of a physical drinking card"
  thd_promise_name: "Time Efficiency"
  thd_promise_text: "Optimization internal processes with the data collected"

how:
  - name: "User App"
    text: "An app for users to interact with the establishment."
  - name: "Staff App"
    text: "An app for every task an establishment performs."
  - name: "BackOffice App"
    text: "Made especially for the management tasks."
  - name: "A Special Card"
    text: "The key to connect every app."

deployment:
  title: "Find out more about our system"
  solutions:
    - text: "A mobile app for a user to interact with the system"
      role: "Consumers"
      platform: "Android"
      link:  /consumers
      index: 1
    - text: "A mobile app for every job an employee might have"
      role: "Employees"
      platform: "Android"
      link:  /businesses
      index: 2
    - text: "A website for management tasks"
      role: "Managers"
      platform: "Website"
      link:  /businesses
      index: 3

history:
  titleText: "Our Mission"
  text: "As a group of young people who have a very active night life and a background in computer science and engineering, we began to take notice of how most nocturnal establishments have a decayed maner of operating. As the end of the night approaches, we find ourselves trapped in an everlasting queue of people that are all trying to pay and head home. Since everyone is eager to leave, we often witness a display of violent behaviours, with people pushing and swearing, leaving us feeling  unsafe. Through the pains we suffered, as consumers, we found an opportunity of business that could solve our problems. By turning nocturnal establishments digital, we could eliminate consumer’s pains and help the business."

mission:
  text:
    - para: "A felicidade está nos pequenos momentos vividos com as pessoas que mais gostamos. Os sorrisos, as gargalhadas, as danças e até mesmo as canções fazem com que nos sintamos mais vivos que nunca. A batida de uma música no ouvido, a sincronização do batimento do coração e aquela troca de olhares sorrateira explodem as nossas sensações e impedem-nos de dizer que não aos momentos. O Nite é conforto, é segurança, é alegria, é, na verdade, o momento. É a razão para que nenhum destes momentos seja perdida. É a resposta às preocupações quando as pessoas saem à noite."
    - para: "Seremos um sinónimo que tudo correrá bem, que as pessoas se podem divertir que, nós, tratamos do resto. Permitiremos aos nossos consumidores aproveitar o agora e deixar os problemas de lado. Lembrá-los-emos dos amigos e prometeremos que um sorriso nunca mais será o mesmo."
    - para: "Seremos uma referência, um símbolo de segurança e o sexto sentido para que boas coisas aconteçam, em qualquer estabelecimento e em qual lugar."

consumerfeatures:
  features:
    - icon: "fas fa-mobile-alt"
      name: "Digital Bill"
      text: "Check your bill in your phone."
    - icon: "fas fa-shield-alt"
      name: "Card Control"
      text: "Control your card remotely"
    - icon: "fas fa-book"
      name: "Digital Menu"
      text: "Consult the menu of an establishment"
    - icon: "fas fa-credit-card"
      name: "Mobile Payments"
      text: "Pay on your device"
  titleText: "The app you have been asking for"
  text: "Take your experience in a nightclub or a bar to the next level."

consumerbilling:
  titleText: "Check your bill"
  text: "Tap into your phone and always find out how much are you paying and what have you drunk already in a matter of seconds."
  img: "/assets/img/userswithout/billinginfo.png"

cardcontrol:
  titleText: "Lost your card?"
  text: "Loosing your card has never been so easy to solve. Control your card remotly, block it in case of loosing it and no one else will be able to buy a drink with your card."
  img: "/assets/img/userswithout/cardinfo.png"

mobilepayment:
  titleText: "Pay on your phone"
  text: "Avoid unecessary queue at the exit, pay in two seconds on your device and leave before everyone else."
  img: "/assets/img/userswithout/paymentcredit.png"

digitalmenu:
  titleText: "Digital Menu"
  text: "Check the price of each drink inside a establishment, choose what you want to drink."
  img: "/assets/img/userswithout/menu.png"

consumerimagecaroussel:
  - img: /assets/img/userswithout/screencard.png
  - img: /assets/img/userswithout/billinginfo.png
  - img: /assets/img/userswithout/cardinfo.png
  - img: /assets/img/userswithout/paymentoptions.png
  - img: /assets/img/userswithout/cardpaid.png
  - img: /assets/img/userswithout/paymentcredit.png
  - img: /assets/img/userswithout/menu.png
  - img: /assets/img/userswithout/guestcode.png


platform:
  titleText1: "One Platform"
  titleText2: "Multiple Estabelishments"
  text: "A platform that brings together multiple estabelishments in the same system."
  costumerButton: "For Customers"
  ownersButton: "For Owners"

cardowners:
  title: "A new type of card"
  text: "Our clients use a new type of card which offers an interface to communicate with our system. This replaced any drinking card previous given by the establishment to a costumer."

bussystems:
  title: "System Requirements"
  text: "Our clients must use a set of products to fully take advantage of our platform."
  requirements:
    - icon: "icon-credit-card"
      name: "NFC Card"
      text: "A card to interact with our system"
    - icon: "icon-screen-smartphone"
      name: "Staff App"
      text: "An app to accomplish any tasks a staff member has"
    - icon: "icon-screen-desktop"
      name: "Management Service"
      text: "A management solution for managers"

stafffeatures:
  title: "The app for every staff task"
  text: "A fast, easy and intuitive solution for the daily challenges a staff member faces."
  features:
    - icon: "icon-credit-card"
      name: "Activate card"
      text: "Each card must be activated before given to a costumer."
    - icon: "icon-lock"
      name: "Control a user's card"
      text: "What to kick a costumer or forbide him of drinking again?"
    - icon: "fas fa-shopping-cart"
      name: "Sell products"
      text: "Credit establishment products into a costumer card"
    - icon: "fas fa-book"
      name: "Check Card Data"
      text: "See what a costumer has consumed, set the card to paid or reset it if a costumer wants to leave."
  images:
    - "/assets/img/staff/menu.png"
    - "/assets/img/staff/activatesearch.png"
    - "/assets/img/staff/cardapio.png"
    - "/assets/img/staff/lock.png"
    - "/assets/img/staff/pay.png"

managerfeatures:
  title: "A management website to keepup with every going on"
  features:
    - name: "Menu management"
      icon: "fas fa-shopping-cart"
      text: "Control the selling products and its prices"
    - name: "Human Resources"
      icon: "fas fa-users"
      text: "Manage your employees"
    - name: "Guest Lists"
      icon: "far fa-handshake"
      text: "Keep track of how your promoters are doing"
  images:
    - img: "/assets/img/manager/menu.png"
      name: "Menu management"
      index: 1
    - img: "/assets/img/manager/rh.png"
      name: "Human Resources"
      index: 2
    - img: "/assets/img/manager/rh.png"
      name: "Guest Lists"
      index: 3
# {{ site.data.sitetext.ex.ex | markdownify | default: example }}
